### ISSUE TITLE
Only opens steam big picture the closes

### ISSUE THREAD

**Issue by masterblaster221** [FrogTheFrog/moondeck#1]
Just crashes on moonlight launch. on all my games it opens big picture then closes saying steam has failed to launch. Oh but great idea of a plugin when it gets fixed it will be my top homebrew plugin and I got it off of the homebrew testing store on steam deck if that matters at all. I hope you continue this it's very cool.

**Comment by FrogTheFrog** [comment]
Heyo,

this should have been fixed by https://github.com/FrogTheFrog/moondeck/commit/e9cde607ceed0d6cb319d4682ae1d9c7cf4f5aeb. Unfortunately, this fix is yet to reach the testing store.

Once the tester confirms that this issue has been addressed, I will close this.

**Comment by FrogTheFrog** [comment]
@masterblaster221 latest version has been pushed to testing (your moondeck config will be discarded FYI due to some config changes) and buddy has been pushed down back to v1.0.0.

In the future there will be actual release versions, but until v1.0.0 is released I will not bump it.

**Comment by masterblaster221** [comment]
It's fixed thanks.
