### ISSUE TITLE
Error on launch and no controller inputs

### ISSUE THREAD

**Issue by KrisCris** [FrogTheFrog/moondeck#10]
Video recording: https://streamable.com/yt9mcc

FYI I am on steamOS beta channel 3.4.4.

**Comment by FrogTheFrog** [comment]
@KrisCris what other plugins do you have installed? The props issue seems to be coming from ProtonDB plugin.

Regarding the "no controls" issue, can you verify that you also have no controller input when streaming directly via moonlight? If you don't, I would guess that ViGemBus is not installed on host.

**Comment by KrisCris** [comment]
Yeah, I have that installed.

But I cannot test after upgrading to the latest version rn, moondeck keeps saying SSL Verification Failed...

**Comment by FrogTheFrog** [comment]
@KrisCris Try now

**Comment by FrogTheFrog** [comment]
I swear to god, this timing... The moment I have decided to trigger a build they pushed MoonDeck to the store...

**Comment by FrogTheFrog** [comment]
> @KrisCris Try now

By that I mean download the latest Buddy version

**Comment by FrogTheFrog** [comment]
Also on Sunshine's discord I glanced at a message that said something along the lines of Windows update breaking the ViGemBus. The fix was to reinstall it.

**Comment by KrisCris** [comment]
> Also on Sunshine's discord I glanced at a message that said something along the lines of Windows update breaking the ViGemBus. The fix was to reinstall it.

I am going to try that! Just manually installed ViGemBus minutes ago but didn't seem to work.

**Comment by FrogTheFrog** [comment]
Can you test if you still don't have input if you just use Moonlight client that is started just as a non-Steam game?

**Comment by KrisCris** [comment]
> Can you test if you still don't have input if you just use Moonlight client that is started just as a non-Steam game?

Tested in both desktop and game mode, no input.

**Comment by FrogTheFrog** [comment]
If you have another PC, install moonlight on it and then at least you'll know if it's the host PC or steamdeck issue

**Comment by KrisCris** [comment]
I somehow fixed the error message by reinstalling some plugins and restarting the system.

For the input, reinstalling ViGemBus and then rebooting the system made it work.
