### ISSUE TITLE
Feature Request - Turn off and on HDR - variable Resolution

### ISSUE THREAD

**Issue by Maz111111** [FrogTheFrog/moondeck#13]
Hi, thank you for the great implementation of this great idea.
I have a feature request and I don't know if this belongs here or in the buddy.
Is there a chance you're programming a function that turns off HDR on the host in Windows when the stream starts and turns it back on when the stream ends. 
Would it also be possible for a function to be built in that makes the resolution variable. It is certainly sufficient to reduce the resolution to that of the Steam Deck. In my opinion, it looks a little better if you stream in a higher resolution in aspect ratio 16:10 (e.g. 2516 x 1600). Many Thanks

**Comment by FrogTheFrog** [comment]
Hello!

> Is there a chance you're programming a function that turns off HDR on the host in Windows when the stream starts and turns it back on when the stream ends.

Unfortunately no - I don't have HDR so no way for me to develop it in the first place. However, Sunshine is coming out with HJDR support soon, maybe it will have some options? Also you can use https://github.com/bradgearon/hdr-switch to toggle the HDR when starting/ending stream with sunshine's DO/UNDO commands:
![image](https://user-images.githubusercontent.com/22381748/214234036-1cdfcadb-277f-467d-a26b-275cbfd944b8.png)

> Would it also be possible for a function to be built in that makes the resolution variable. It is certainly sufficient to reduce the resolution to that of the Steam Deck. In my opinion, it looks a little better if you stream in a higher resolution in aspect ratio 16:10 (e.g. 2516 x 1600).

It is already doable. In Host Settings you need to scroll down to add custom resolutions and then select one to use. Once added they can also be toggled via quick access menu. Or did you mean something else?

**Comment by Maz111111** [comment]
Many thanks for your response. I'll try the resolution thing tonight.
Unfortunately, the HDR story doesn't work that way. Sunshine won't start as long as HDR is turned on in windows. That's why I have to stay with the nvidia solution for as long as possible.
If you have an HDR monitor, you will probably have HDR permanently switched on in the Windows settings.
If you now stream games to a device that is not HDR capable (regardless of the software), the colors are so oversaturated that they are unplayable.
I currently solve this with Moonlight by "streaming" a batch file that first sets the resolution and then runs a script that first sends "win"+"alt"+"B" to the system - this creates HDR turned off in Windows - and then starts Playnite. The script then waits until playnite is finished and sends "win"+"Alt"+"B" again to turn HDR back on.
I had thought that you could install a switch in the host settings of the plug-in, with which the user could initiate exactly this procedure (instead of playnite the script would have to wait until the game is closed).
But I think I'm exaggerating. It makes sense for everyone who programs in this field to focus on sunshine after nvidia made this stupid decision - so thank you again for your great work.

**Comment by FrogTheFrog** [comment]
Well good news for you that they are working on this:
![image](https://user-images.githubusercontent.com/22381748/214252846-e6847583-7b3d-4e3f-80ae-d5de4e9be14b.png)

**Comment by Maz111111** [comment]
Your great! I'll give it a try! THX

**Comment by FrogTheFrog** [comment]
So, as I will not be implementing the HDR thingy and custom resolutions are allowed in the plugin, I will be closing the issue.
