### ISSUE TITLE
"Letter Box"/Black Bars surrounding the image when docked to a 1080p TV

### ISSUE THREAD

**Issue by XenHat** [FrogTheFrog/moondeck#14]
I'm not quite sure if this is an issue with Linux only, but I have a strange "Letter Box" issue when playing through MoonDeck while docked to a TV.

This issue does not happen when using Steam's build-in Remote Play.
Testing this when not docked is difficult as my monitors do not support 16:10 virtual resolution, so I do get letter boxing whenever I stream onto the Deck's display.

Phone recording of the issue: https://cdn.discordapp.com/attachments/446585252949917706/1071594659291332618/20230204_195131.mp4

**Comment by FrogTheFrog** [comment]
Have some investigation requests for it:

- Does this happen when using the MoonDeck's "change resolution" option or without?
- If you start the stream via the MoonDeck button, exit (like in the video) and then start streaming manually via Moonlight -> MoonDeckStream, does it also happen?
- Can you try to replicate this without MoonDeck, just start the Moonlight's Desktop stream, start the game and then click the button combination to close the Moonlight without killing the stream. Then start the stream again.
- And finally:

What does the box say?
![image](https://user-images.githubusercontent.com/22381748/216810989-7e8d621f-b745-473c-87d6-e152c80a5ddd.png)

**Comment by XenHat** [comment]
> What does the box say?

That's just Death Stranding being silly and asking if I want to close the game after it received the SIGKILL signal from quitting the stream.

I will test these bullet points and report in a new comment as soon as possible!

**Comment by FrogTheFrog** [comment]
Ah, is it possible that Steam crashes on host?

**Comment by XenHat** [comment]
> Ah, is it possible that Steam crashes on host?

According to my tmux logs (I run steam in a tmux session for debugging), steam does not seem to crash at all.

**Comment by FrogTheFrog** [comment]
Can you check somehow if the code at line 205 is triggered somehow https://github.com/FrogTheFrog/moondeck-buddy/blob/main/src/lib/os/steamhandler.cpp?

**Comment by FrogTheFrog** [comment]
Because then it would be me sending the killbill signal...

**Comment by XenHat** [comment]
> Can you check somehow if the code at line 205 is triggered somehow https://github.com/FrogTheFrog/moondeck-buddy/blob/main/src/lib/os/steamhandler.cpp?

Sorry for the confusion. The error box from Death Stranding only happens when I select "Quit Game" on the steam deck's UI from within a Steam Remote Play session, which was necessary to use for the comparison video. It does not trigger when using the gamepad shortcut to disconnect the stream.

**Comment by XenHat** [comment]
Recapping some debugging that happened on Discord:

**I had steam's "Resolution" dropdown overriding moonlight's resolution to 1200x800, so it had no choice but display that. Changing it to "Native" fixed the issue.**

**Comment by FrogTheFrog** [comment]
Wiki page created and documented :)
