### ISSUE TITLE
MoonDeck Stream Quality Settings?

### ISSUE THREAD

**Issue by TheDenunci** [FrogTheFrog/moondeck#15]
Heya, I know that Moonlight allows you to set the bitrate that the host computer will stream at, but I'm unsure if there's an option to do so here in MoonDeck?

**Comment by FrogTheFrog** [comment]
I will try to add it soon'ish. No slider though, because I want to have it as optional value.

**Comment by FrogTheFrog** [comment]
@TheDenunci you can now get the latest release from the testing store with the bitrate override option added :)
