### ISSUE TITLE
[Wiki] Better pictures for the troubleshooting page

### ISSUE THREAD

**Issue by XenHat** [FrogTheFrog/moondeck#16]
I noticed you grabbed screenshots of my video, so I took it upon myself to provide better pictures from a capture card 😄 

![moondeck_letterbox_issue](https://user-images.githubusercontent.com/980408/217090520-2ad89c49-0c62-4e89-ad78-560f526c8bfd.png)
![moondeck_scaling_correct](https://user-images.githubusercontent.com/980408/217090531-b2405f7b-3193-46d6-9408-485eee0b9e75.png)

**Comment by FrogTheFrog** [comment]
Thanks! Although the old ones also had some charm to it, at least with these ones I won't get blind just by opening the page :D
