### ISSUE TITLE
MoonDeck does not work after the Steam Client 2/17 beta update

### ISSUE THREAD

**Issue by dshk0718** [FrogTheFrog/moondeck#17]
The issue is what the title describes. MoonDeck no longer works after this new Steam Client Beta update. You cannot open settings and it doesn't find any of the host settings.

I did find a workaround for this for now though. Going to Steam Client "Stable" and reinstalling Decky Loader as "Stable" does work.

**Comment by FrogTheFrog** [comment]
Already working on it. Almost every plugin is broken on beta... Ty Valve!

**Comment by dshk0718** [comment]
Glad to hear that! And yeah, seems like so... lol

**Comment by FrogTheFrog** [comment]
Fix is now in the store.
