### ISSUE TITLE
"Go to Settings" routes to empty page

### ISSUE THREAD

**Issue by kimeikato** [FrogTheFrog/moondeck#2]
After installation I tried to configure my setting, but it only shows an empty page

https://user-images.githubusercontent.com/13108952/206877630-3cd09851-4b0f-456a-9f39-ac7e0319f951.mp4

![photo_2022-12-10_23-29-38 - Kopie](https://user-images.githubusercontent.com/13108952/206877700-e3d8e86c-2e6c-4748-97a3-99db12284841.jpg)
![photo_2022-12-10_23-29-34 - Kopie](https://user-images.githubusercontent.com/13108952/206877702-3c67d2e1-4bba-4c8b-abc0-95ab1480734d.jpg)

**Comment by FrogTheFrog** [comment]
It works on stable, but is broken on bet.

It is already fixed and is in the "Testing" store (or whatever it is called). A v1.1.0 was pushed just a few minutes ago to it and it will also require for you to update Buddy to v1.1.0 just so you know.

**Comment by FrogTheFrog** [comment]
And v1.0.0 is broken at the moment :D

**Comment by alexbowe** [comment]
Came up against this issue just now while installing Moondeck + Moondeck Buddy for the first time (although I've been using Moonlight on the deck via the client). When I try to pair it with my computer, a box pops up with the code I need to enter, but the Steam Deck has a blurred screen and nowhere to input it. Restarting/reinstalling hasn't helped.

**Comment by DreamboxMinerva** [comment]
> Heyo @alexbowe , modals are currently broken on Decky, on Steam beta.
> 
> Possible solutions:
> 
> 1. switch to stable for pairing
> 2. pair manually:
>    In the desktop mode you will find `~/.config/mondeck/settings.json`. It will contain client Id string. Let's say it's `"123455-4326"`. Once you have it, you can go to the host PC, locate the `MoonDeckBuddy.exe` and create a file called `clients.json` in the same directory. Inside it paste the id like this `["123455-4326"]`. Restart the Buddy and it should be paired.

Not working for me :/ the stable release as the same issue stated by alexbowe, and I followed the second solution, entered the string to a new clients.json file and in moondeck the "pair" button gets greyed out and a loading icon keep appearing with nothing else

**Comment by FrogTheFrog** [comment]
@DreamboxMinerva can you post a screenshot?

**Comment by DreamboxMinerva** [comment]
Nevermind, I finally managed to make it work, what I did was deleting everything moondeck related on both the deck and my PC, downloaded everything again, and this time I manually paired both device as soon as the plugin was installed, without touching **anything** in the plugin menu and it worked this way.

During my failed attempt, I kept clicking on "pair" in the moondeck menu to get the window asking for a number on my Host PC, closing it and then doing the pairing manually, and by doing this I had the issue described.

**Comment by FrogTheFrog** [comment]
Resolved in the latest release

**Comment by Pleasant-exe** [comment]
> Heyo @alexbowe , modals are currently broken on Decky, on Steam beta.
> 
> Possible solutions:
> 
> 1. switch to stable for pairing
> 2. pair manually:
>    In the desktop mode you will find `~/.config/mondeck/settings.json`. It will contain client Id string. Let's say it's `"123455-4326"`. Once you have it, you can go to the host PC, locate the `MoonDeckBuddy.exe` and create a file called `clients.json` in the same directory. Inside it paste the id like this `["123455-4326"]`. Restart the Buddy and it should be paired.

Did not work for me
