### ISSUE TITLE
"Failed to find application MoonDeckStream" documentation improvement

### ISSUE THREAD

**Issue by LarsCelie** [FrogTheFrog/moondeck#22]
Initially I had the error message "Failed to find application MoonDeckStream".

This was because my moonlight client was connecting to nvidia gamestream instead of sunshine.
In order to fix it, I had to disable the nvidia gamestream in the geforce experience, and delete the host pc via de moonlight client.

Perhaps something to add to the troubleshooting wiki?
Took me 2 hours I don't wish on anyone.

Works now btw, so thanks for that!

**Comment by FrogTheFrog** [comment]
Docs have been updated: https://github.com/FrogTheFrog/moondeck/wiki/Troubleshooting#failed-to-find-application-moondeckstream

**Comment by LarsCelie** [comment]
Damn you're quick. Well done! it looks better than I tried explaining it.
