### ISSUE TITLE
Custom resolution decreases quality

### ISSUE THREAD

**Issue by Genadiii** [FrogTheFrog/moondeck#23]
For several days I tried to understand if my connection sometimes drops stream quality or when using the moondeck plug-in, the quality is worse than when just using moonlight directly.

It turned out that for some reason the quality is worse and blocky when starting stream via the plugin.
I'm using custom resolution 2560x1600.
My settings in moonlight: 800p 150 Mbps
Results:
Moonlight directly, host resolution 4k, in game 1600p - no artifacts
Moonlight directly, host resolution 4k, in game 800p - no artifacts
Moonlight directly, host resolution 1600p, in game 1600p - no artifacts
Moonlight directly, host resolution 1600p, in game 800p - no artifacts
Moondeck, no pass resolution and bitrate, in game 1600p - no artifacts
Moondeck, no pass resolution and bitrate, in game 800p - no artifacts
**Moondeck, pass 1600p, in game 1600p - blocky artifacts
Moondeck, pass 1600p, in game 800p - no artifacts, but quality seems to be worse**
Moondeck, pass 800p, in game 1600p - no artifacts
Moondeck, pass 800p, in game 800p - no artifacts

So, using custom resolution in moodeck samehow decreases quality.
Maybe because it also forces the stream resolution to 1600p?
If I disable "Pass the resolution and bitrate options to Moonlight..." but keep enabled "Try to apply SteamDeck's current resolution on host PC" then sadly the resolution on host will be not applied.

I would like to have 1600p on host. The streamed games look much better and sharper when they are rendered at 1600p on host. And if the host is set to 1600p then the borderless games will be also rendered at 1600p and some games won't let you set 1600p if the host resolution is 800p.

**Comment by FrogTheFrog** [comment]
I have already renamed the "Try to apply SteamDeck's current resolution on host PC" as it is misleading, but what it means it will use the 800p as a fallback (in your case) if the custom resolution is disabled.

> If I disable "Pass the resolution and bitrate options to Moonlight..." but keep enabled "Try to apply SteamDeck's current resolution on host PC" then sadly the resolution on host will be not applied.

I have tried the following:
1. Set custom resolution to 2560x1600;
2. Enabled custom resolution;
3. Disabled "Pass the resolution and bitrate options to Moonlight".

In my case it works as expected, host is resized to 2560x1600 and Moonlights default settings are used (verified this by setting a very low bitrate to get it blocky and then increased it on the next try).

> Moondeck, pass 1600p, in game 800p - no artifacts, but quality seems to be worse

This would be expected as the Moonlight has to upscale it now (I think).

> Moondeck, pass 1600p, in game 1600p - blocky artifacts

My guess is that you did not set a bitrate in the MoonDeck. What happens is that Moonlight automatically calculates it for you if you don't pass it along with resolution, so try setting it to 150000.

**Comment by FrogTheFrog** [comment]
> sadly the resolution on host will be not applied

I have no idea why that happens in your case :?. Is the custom resolution also disabled?

**Comment by Genadiii** [comment]
> My guess is that you did not set a bitrate in the MoonDeck. What happens is that Moonlight automatically calculates it for you if you don't pass it along with resolution, so try setting it to 150000.

I have set 150000 in both moonlight and moondeck

> I have no idea why that happens in your case :?. Is the custom resolution also disabled?

After I reisntalled everything it works! So in my case disabling "Pass the resolution and bitrate options to Moonlight", enabling custom resolution 2560x1600 and and Moonlight stream 800p gives me the best image quality.

Still wondering why 2560x1600 stream and 2560x1600 rendering resolution looks so bad and blocky in some scenes. There can't be not enough bandwidth.

**Comment by FrogTheFrog** [comment]
As it seems that your issue is resolved, I will be closing this issue.

**Comment by Genadiii** [comment]
Yes, thanks for your help :)

A small feedback. I find the description of this setting "Pass resolution and bitrate settings to Moonlight" a bit misleading. I mean the part "I honestly don't know why I added option to disable this...". After reading this, it looks to me like something that should only be disabled in a very unusual case. But it turned out that in my case this is exactly what needed to be disabled. And also I think most people have already set their desired stream resolution and bitrate in moonlight and overwriting it by moondeck is pointless. 
Therefore, I think this option should be disabled by default, and enabling it is an unusual case where the user needs for some reason to overwrite already configured moonlight settings.

**Comment by FrogTheFrog** [comment]
@Genadiii it is enabled by default, because it works better with external displays (I have 2 which I switch often) and I have never thought about downscaling before if I'm honest.

I do agree that it looks better than just 800p, but it also looks the same to me when 1600p is passed to Moonlight. Maybe more bandwidth is used.

Therefore, I would to keep it as a default option, however I do think that the comment should be improved and any suggestions would be welcome :D, but I have no idea what it should be like apart from "Disable this option if you want to use the pre-configured/existing Moonlight settings for the Gamestream"

**Comment by Genadiii** [comment]
> I do agree that it looks better than just 800p, but it also looks the same to me when 1600p is passed to Moonlight. Maybe more bandwidth is used.

For it me also mostly looks the same when 1600p is passed, only some scenes are very blocky and look high compressed. I would have thought that it looks the same if I did't find where it looks bad. For example water in Nier Automata. The water in this game looks very grainy when played natively (both steam deck and pc with 4k display). Maybe because of this, stream at 1600p with water in the screen looks very blocky. I haven't noticed this problem in other games... Maybe it is just an edge case for encode/decode/stream. And I don’t think that there could be a problem with my configuration: PC - Ethernet connection (1 gigabit) and the steam deck - wifi 5 connection (tested near the router for the best signal).

> Therefore, I would to keep it as a default option, however I do think that the comment should be improved and any suggestions would be welcome :D, but I have no idea what it should be like apart from "Disable this option if you want to use the pre-configured/existing Moonlight settings for the Gamestream"

Maybe something like "Use steam deck native(or custom) resolution and specified bitrate instead of the existing Moonlight settings for the Gamestream"
