### ISSUE TITLE
Request / question: Change bitrate within moondeck?

### ISSUE THREAD

**Issue by philhzss** [FrogTheFrog/moondeck#26]
Hi!

Really love this plugin. I was wondering, is there a way to change the bitrate (Moonlight setting) within Moondeck?

For context, I stream from two locations, at home when docked with ethernet I like to use high bitrate (75+ mbps) as it's all local and it works well. 

However, when away from home and on wifi, I need too lower my bitrate to 10-15 mbps for it to work properly. 

Currently the only way I've found to do that is to open the Moonlight app on its own, and change the settings there. I often forget though when switching between home and away, so I'll launch a game through Moondeck, realise I forgot, then I'll press Start+Select+L1+R1 to change settings, but that will close Moondeck so I need to manually go to the Moonlight app to change the bitrate again. 

I tried creating a duplicate of my PC profile (one with the high bitrate, one with the low bitrate) in Moonlight, but that doesn't work, it only keeps one PC entry for the same machine. 

Do you think you could add a bitrate setting to Moondeck? Or perhaps is there already a way to do this and I'm missing it?

Thank you!

Phil

**Comment by FrogTheFrog** [comment]
Heyo,

check the host settings in MoonDeck. In your case you should add 2 custom resolutions with different bitrates.

Those options will the he visible in quick access menu.

Cheers!

**Comment by philhzss** [comment]
OH!!!!

Thank you!!! Got it!! I hadn't realised you could set different bitrates like that!

That works perfectly! Thank you!!
