### ISSUE TITLE
Feature Request - Enter Host IP

### ISSUE THREAD

**Issue by profblackjack** [FrogTheFrog/moondeck#3]
The normal Moonlight client has trouble scanning for nvidia gamestream broadcasts in my network, but everything works fine when I enter my host pc's IP address. Would love if moondeck gave me the same option, as right now the scan button comes up with 0 hosts.

**Comment by FrogTheFrog** [comment]
Sounds easily doable. Will start working on it :+1:

**Comment by FrogTheFrog** [comment]
@profblackjack it's in the "Testing" store. Please check if it works for you.

**Comment by profblackjack** [comment]
@FrogTheFrog Wow, incredible turnaround time!

I can confirm the new field works like a treat, successfully streaming from my pc to my deck.

**Comment by FrogTheFrog** [comment]
Glad to hear it :). I will close this issue once it is released to the "Stable" store.

**Comment by FrogTheFrog** [comment]
Feature is in the latest release
