### ISSUE TITLE
Add host selection to Moondeck quick access menu

### ISSUE THREAD

**Issue by gdiazbanuelos** [FrogTheFrog/moondeck#31]
Hello!

I frequently switch Moonlight hosts and it becomes tedious to dive into the fullscreen settings to change the host. Would it be possible to change the host from the quick access menu as a drop like for the preset custom resolution/bitrate dropdown?

Thank you!

**Comment by FrogTheFrog** [comment]
Heyo,

It should be easily doable. Will take a look once I'm no longer sick.

**Comment by FrogTheFrog** [comment]
@gdiazbanuelos please try MoonDeck from the Testing store.

**Comment by FrogTheFrog** [comment]
Already available in the default store.
