### ISSUE TITLE
Not passing through Steam Deck controller input when using a layout with keyboard input

### ISSUE THREAD

**Issue by GroenteLepel** [FrogTheFrog/moondeck#32]
I had troubles with the controller input not working. I tested it through Moonlight itself in game mode and there it immediately took my controller, I only had these issues when using the moondeck button in my game page. 

This was when playing Horizon Zero Dawn, and Guerilla has a default gamepad layout for that. For some reason, that one messes with the setup. I first though it was because I have a hotweel menu set up with some keyboard inputs (like `M` for map, `I` for inventory) so I swapped back to the default Guerilla input, but the issues remained. I finally swapped to the Steam Deck default "Gamepad With Joystick Trackpad" and then it finally worked. Is there a way to maybe force the gamepad connecting so I can use both keyboard and gamepad, or otherwise some form of error should occur?

**Comment by GroenteLepel** [comment]
All right I tried mapping some keyboard keys to the default "Gamepad With Joystick Trackpad" template and that works. There's probably some issue with the Guerilla default layout not properly passing through.

**Comment by FrogTheFrog** [comment]
If the default layout uses Steam Controller API or something to directly communicate with the game, it will not work and there is nothing that can be done about this sadly.

Anyway, since you've solved this on your own, I'm closing this.
