### ISSUE TITLE
Add support for domains in manual host selection

### ISSUE THREAD

**Issue by RedStealthDev** [FrogTheFrog/moondeck#33]
I tried to add my sunshine host to moon deck and it wont allow me because it needs a ipv4 address and since i use a domain to simplify my hosting i would rather use the domain in exchange for my dynamic ip. Also when my dynamic ip changes it changes on the domain automatically

**Comment by FrogTheFrog** [comment]
I have removed the limitation for the address and it's already in the Testing store.

I've tested this locally only by editing the hosts file, so please let me know if this works for you

**Comment by FrogTheFrog** [comment]
Added
