### ISSUE TITLE
Pairing doesn't work

### ISSUE THREAD

**Issue by rossjohnson87** [FrogTheFrog/moondeck#34]
Just a heads up, went through troubleshooting steps to a T, can get the pair prompt and enter the 4 digits but status won't change to paired. Might be a new issue/persistent one. Let me know if you want any logs or to try anything to fix.

**Comment by FrogTheFrog** [comment]
Heyo,

please try restarting SteamDeck and Host. Usually it helps, given that you have had a pop-up from Buddy.

**Comment by distraughtklownz** [comment]
Hey, I'm having the exact same issue. I am able to get a pairing code and get the host to show "Online," but never "Paired." Once connected, I am able to use all the side panel commands (Shutdown, Restart, etc.), but I am not able to stream from it.

I am able to use Moonlight normally, and I can use Moonlight to run MoonDeckStream without any issues, but it will not connect directly from Moon Deck. I have ensured that all the firewall settings are in place, I have restarted both multiple times, and done fresh installs of Moon Deck and Sunshine.

**Comment by FrogTheFrog** [comment]
> Hey, I'm having the exact same issue. I am able to get a pairing code and get the host to show "Online," but never "Paired." Once connected, I am able to use all the side panel commands (Shutdown, Restart, etc.), but I am not able to stream from it.
> 
> I am able to use Moonlight normally, and I can use Moonlight to run MoonDeckStream without any issues, but it will not connect directly from Moon Deck. I have ensured that all the firewall settings are in place, I have restarted both multiple times, and done fresh installs of Moon Deck and Sunshine.

You're paired already. That aside please post logs from Sunshine

**Comment by distraughtklownz** [comment]
> > Hey, I'm having the exact same issue. I am able to get a pairing code and get the host to show "Online," but never "Paired." Once connected, I am able to use all the side panel commands (Shutdown, Restart, etc.), but I am not able to stream from it.
> > I am able to use Moonlight normally, and I can use Moonlight to run MoonDeckStream without any issues, but it will not connect directly from Moon Deck. I have ensured that all the firewall settings are in place, I have restarted both multiple times, and done fresh installs of Moon Deck and Sunshine.
> 
> You're paired already. That aside please post logs from Sunshine

https://pastebin.com/gPZpLkxa
![IMG_1880](https://github.com/FrogTheFrog/moondeck/assets/104905015/0f769a6b-b008-45b9-9b53-17f1f8331760)
The GameStream and Buddy status shows online for both, but has the loading icon next to it just spinning forever.

**Comment by FrogTheFrog** [comment]
The spinning icons are okay'ish, it usually means that it takes a while (> 1s) to hear back from the host, but if it still says it's online, it means it heard back from it in the end.

As for the logs, please post one after you try to start streaming via MoonDeck.

**Comment by distraughtklownz** [comment]
@FrogTheFrog I figured it out. You were right about everything already being paired. 

For some reason, MoonDeck was not syncing the apps from Sunshine automatically which is what made me think it wasn't working properly. What I did to do to get my games to show up was: MoonDeck settings -> Sunshine Apps -> Sync all apps through Buddy 

I didn't expect this to do anything because it the status updated to "paired" from only "online," but to my surprise it synced all apps and successfully added them as Non-Steam games. Not sure why this part of the process failed repeatedly, but I got it going. Thanks for the assist!

**Comment by FrogTheFrog** [comment]
> For some reason, MoonDeck was not syncing the apps from Sunshine automatically which is what made me think it wasn't working properly. What I did to do to get my games to show up was: MoonDeck settings -> Sunshine Apps -> Sync all apps through Buddy

Ah, that was a mistake on my part as I didn't even think you were talking about that. This "Sync" thing that you're using is a secondary feature that I've added just because I was lazy :P. FYI, non-Steam games (Sunshine apps) will not sync anything automatically - you always have to do it manually.

**Comment by FrogTheFrog** [comment]
I'm closing the issue since the OP is gone...
