### ISSUE TITLE
"Buddy refused to launch Steam app"

### ISSUE THREAD

**Issue by HollyCeuin** [FrogTheFrog/moondeck#35]
Hi, upon launching _any_ game I get about a second of the desktop, the stream closes and a notification pops up on the deck saying "Buddy refused to launch Steam app, check..."

I'm on linux, specifically Pop_OS! if that helps. Sunshine is installed and configured, v0.21.0, Steam is installed to `/home/holly/.steam` and I symlinked it to `/usr/bin` in order to get buddy to even start.

This happens with every game, whether Steam is open or not.

[moondeckbuddy.log](https://github.com/FrogTheFrog/moondeck/files/13353661/moondeckbuddy.log)
[moondeckstream.log](https://github.com/FrogTheFrog/moondeck/files/13353662/moondeckstream.log)

**Comment by FrogTheFrog** [comment]
Heyo o/

Buddy is complaining that `/usr/bin/steam steam://open/bigpicture` does not work. Can you launch it via the terminal?

**Comment by HollyCeuin** [comment]
Thanks for replying so quickly!

If I run that, I get:
`bash: /usr/bin/steam: Is a directory`

**Comment by FrogTheFrog** [comment]
Well, how do you launch steam from terminal?

**Comment by HollyCeuin** [comment]
It would just be `steam://open/bigpicture`

Seems like changing the steam binary override in the config file has fixed this, though, although now I have a new issue in that when big picture launches, it minimizes/restores about 3 times a second on loop. No idea how to deal with that.

**Comment by FrogTheFrog** [comment]
Now it's a linux "feature" you're dealing with. You could configure MoonDeck to always close steam afterwards, or Buddy to not enforce the big picture mode (which comes with a caveat that you have to click through the launchers, if any).

**Comment by HollyCeuin** [comment]
Disabling big picture in the config fixed that and now everything works. Thanks so much for the help!
