### ISSUE TITLE
Add support for resolution supersampling or custom resolutions 

### ISSUE THREAD

**Issue by xtrilla** [FrogTheFrog/moondeck#36]
First sorry if this is already a feature and I don’t know how to find it, also this is a feature suggestion not an issue (If this is the wrong place for it please let me know).

Quality of moonlight streams is better if super sampling. For example 2560x1600 gives better quality than 1280x800.

As there is a custom bitrate or fps field would it make sense to have a custom resolution field as well or a slider with a multiplier? (To have 1920x1200jj and 2560x1600).

Obviously this can also be set in moonlight directly, but considering moon deck can handle resolution changes on the host, custom fps and bitrate maybe adding also a custom resolution field could enhance the experience for users with powerful PCs and WiFi setups.

And in any case, thanks for this software, it’s a beautiful contribution for self hosted game streaming.

**Comment by FrogTheFrog** [comment]
I'm not sure I follow, there is a way to add custom resolutions in MoonDeck and even a way to attach them to displays to be auto-selected.

**Comment by xtrilla** [comment]
I’m sorry, I’m stupid -or lack sleep- I think I did not see the option because I checked and recheck but now while doing other tests I’ve seen it … does it get  disabled if some other option is enabled or I’m basically blind? Sorry and thanks!
