### ISSUE TITLE
Feature Request - Support more precision on FPS declerations

### ISSUE THREAD

**Issue by Nitrousoxide** [FrogTheFrog/moondeck#37]
I have a streaming host (on wayland) that has allowed resolutions and FPS with more precision than I am allowed to set in moondeck.  It appears you can go to at most 2 decimal places in a custom fps.  However running gnome-randr on my end gives me allowed modes with at least 3.

```
              1280x800@143.835	1280x800  	143.84    	[x1.00+, x1.25, x1.50]
              1280x800@119.846	1280x800  	119.85    	[x1.00+, x1.25, x1.50]
               1280x800@89.887	1280x800  	89.89     	[x1.00+, x1.25, x1.50]
               1280x800@59.810	1280x800  	59.81     	[x1.00+, x1.25, x1.50]
```

**Comment by Nitrousoxide** [comment]
Related to:
https://github.com/moonlight-stream/moonlight-qt/issues/1147

**Comment by FrogTheFrog** [comment]
I'm closing this until Moonlight starts accepting non-iteger FPS values
