### ISSUE TITLE
Steam / SteamApp not starting on stream

### ISSUE THREAD

**Issue by TuNdRa-Plains** [FrogTheFrog/moondeck#38]
Latest versions of Moondeck & Buddy, Host is Windows 11 Pro (22631.2861), AMD CPU, Nvidia GPU (No iGPU), Steam Deck is running 3.5.7

Stream launches as expected, but then sits at Desktop. If Steam isn't running; it isn't started by the Buddy. If it is running; no games launch. Stream then times out with "Stream failed to start" toast triggered on the Deck.

I've followed the troubleshooting steps in the Wiki for the failure to launch and the given command works without an issue - I can't see any obvious problems from the logs either.

Frankly; I'm stumped for what else to try, I can't see anything obvious in the logfiles pointing to the issue either;
[moondeckbuddy.log](https://github.com/FrogTheFrog/moondeck/files/13805621/moondeckbuddy.log)
[moondeck-runner.log](https://github.com/FrogTheFrog/moondeck/files/13805625/moondeck-runner.log)
[moondeck-runner-moonlight.log](https://github.com/FrogTheFrog/moondeck/files/13805626/moondeck-runner-moonlight.log)

**Comment by FrogTheFrog** [comment]
It seems that Sunshine is failing to start MoonDeckStream. Please paste the log from Sunshine and a screenshot of the MoonDeckStream app config.

**Comment by TuNdRa-Plains** [comment]
Sunshine logs are below - It doesn't indicate launching anything other than [Desktop] when the stream is connected.

[Sunshine Log.txt](https://github.com/FrogTheFrog/moondeck/files/13806152/Sunshine.Log.txt)

On a whim; I deleted and recreated the MoonDeckStream entry in Sunshine, and despite the fact the two paths looked visibly identical; suddenly it worked repeatedly.

I can't explain why - as both entries had identical names and filepaths.

Only significant change to the setup that I can think of is I'd previously in-place upgraded Sunshine a few days back for another application to work with it, but I really wouldn't have expected that to cause the issue.

**Comment by FrogTheFrog** [comment]
Oh well, we will never know, but at least it works now so I'm closing this :D
