### ISSUE TITLE
Feature Request: Non Steam Games

### ISSUE THREAD

**Issue by stevenbales** [FrogTheFrog/moondeck#39]
Hi, thank you for the plug in! It's far and away my most used plug in and has made my Moonlight experience immeasurably better.

A question though, what would it require to implement launching non steam games? Is it a possible future feature or is there some technical limitation stopping this?

**Comment by FrogTheFrog** [comment]
At the moment there are technical limitations aa Steam does not expose the info about non-Steam games like it does for Steam games.

So the feature will not be implemented for now.

**Comment by XenHat** [comment]
That's a shame, it used to work. I hope this can be resolved eventually.

**Comment by FrogTheFrog** [comment]
> That's a shame, it used to work. I hope this can be resolved eventually.

Wut? It never worked 🤔. Are you talking about Sunshine apps? Those should still work?

**Comment by cyperous** [comment]
Recently today, I was adding a non-steam game to my Windows box, and when I went to non-steam games on my Steam deck, the non-steam game showed up on my Steam Deck. If I opened the game on my steam deck, steam only has the option to steam it. Why can't you add the moon deck icon to these items? If Valve can do it surely you can.

Can we get this issue reopened?

**Comment by FrogTheFrog** [comment]
> Recently today, I was adding a non-steam game to my Windows box, and when I went to non-steam games on my Steam Deck, the non-steam game showed up. If I opened the game on my steam deck, steam only has the option to stream it. Why can't you add the moon deck icon to these items? If Valve can do it surely you can.
> 
> Can we get this issue reopened?
> 
> Those entries might only be present if steam is open on the Windows box and the box is on.

I don't plan to add support for them, because Steam does not provide a reliable way of tracking their process state. I am also preoccupied with Sunshine at the moment.

It might be possible to implement this if Buddy was to observe logs from Steam instead of registry. You're welcome to try it out and submit a PR if you succeed.

**Comment by cyperous** [comment]
As much as I would love to look into it, maybe someday. I realized I could accomplish what I needed by adding the non-steam game as a sunshine app and using moondeck to sync those apps to the Steam Deck’s non-steam library. At the very least, my needs have been met; thanks for building this awesome decky plugin.
