### ISSUE TITLE
Can't access settings page

### ISSUE THREAD

**Issue by jgibson02** [FrogTheFrog/moondeck#40]
The settings button is selectable but does nothing when clicked/pressed, so I'm unable to select a host. Just installed the plugin for the first time, and have tried restarting the Steam Deck a couple times as well as downgrading the Decky version to Stable.
Versions:
MoonDeck 1.6.15 (also tried .14 and .13)
Decky 2.10.10
SteamOS 3.5.13

**Comment by FrogTheFrog** [comment]
Decky is currently broken on preview due to chromium update
