### ISSUE TITLE
Demos don't work

### ISSUE THREAD

**Issue by Pirateguybrush** [FrogTheFrog/moondeck#42]
I've loaded up a bunch of Next Fest titles on my desktop, but they're not showing as streamable on the deck.  I've even installed them on the deck as well to see if that makes a difference, but it doesn't show the badge.

**Comment by FrogTheFrog** [comment]
Yeah, unfortunately it is a limitation that requires a some effort to make it kinda work (all demos would have to be installed on deck).

I'm not going to invest time into this for the demos, sorry.
