### ISSUE TITLE
HDR not working

### ISSUE THREAD

**Issue by ScraggyMcRaggy** [FrogTheFrog/moondeck#43]
Everything is working however Moondeck does not seem to carry over HDR from my PC to the Deck. Is there something wrong? Or does Moondeck not support HDR?

I am pushing res, bitrate, fps settings etc via Moonshine, not Moondeck. However neither carry HDR to the deck.

The Moonshine app supports HDR so I was hoping it would be the same here.

**Comment by FrogTheFrog** [comment]
HDR support is still in development for Moonlight.
