### ISSUE TITLE
Wake on Lan no longer works after 1.7.0

### ISSUE THREAD

**Issue by ScraggyMcRaggy** [FrogTheFrog/moondeck#44]
FYI - Wake on Lan no longer works after latest 1.7.0 update. Worked before the update no problem.

Buddy has been updated to latest version.

Restart/Shutdown still works fine.

Wake on Lan still works using official Moonlight app.

**Comment by FrogTheFrog** [comment]
What MAC address do you see in the host settings page?

**Comment by ScraggyMcRaggy** [comment]
No, Moondeck is using a different adapter's (not in use) MAC address instead.

**Comment by FrogTheFrog** [comment]
Can you give some more info about the other interface? Is it virtual?

**Comment by ScraggyMcRaggy** [comment]
Yeah it's an _ExpressVPN TAP Adapter_. I disabled it and restarted both Buddy and Moondeck, but MAC still defaults to it.

**Comment by FrogTheFrog** [comment]
Please try this build https://github.com/FrogTheFrog/moondeck-buddy/actions/runs/7902248715?pr=79

Unfortunately the framework I'm using does not expose the interface associated with the connection :/, however I've added an override for the MAC address so you can configure it in the settings.

**Comment by ScraggyMcRaggy** [comment]
Sorry, I tried my best, but I have no idea how to produce an exe from this lol. Happy to test for you, but would need a little assistance.

**Comment by FrogTheFrog** [comment]
At the end of the page I've provided it will show artifacts, simply download them and extract.

**Comment by FrogTheFrog** [comment]
You must be logged into GitHub to download them

**Comment by ScraggyMcRaggy** [comment]
Installed and edited the settings file with my MAC address. 

Unfortunately Wake on LAN still doesn't work. Moondeck still displays the old MAC weirdly, not sure if it should be doing that?

I presume Deck/Buddy status changing to 'Exception' is expected?

Image attached of modified setting file. Let me know if I've done something wrong...

![image](https://github.com/FrogTheFrog/moondeck/assets/143287401/b2ff1844-440a-4faa-a89a-faa817599070)

**Comment by FrogTheFrog** [comment]
Ugh 😁

So I didn't have time to document this yet, but I'm enforcing 00:00:00:00:00:00 format, to keep in line with the old formattl...

Please change the separators

**Comment by ScraggyMcRaggy** [comment]
Yay that did the trick! Wake on LAN now working and MAC address is set correctly in Moondeck. 'Exception' status has also changed to 'online.'

Thanks for your help and amazing work.

**Comment by FrogTheFrog** [comment]
New Buddy version released
