### ISSUE TITLE
Moondeck / Buddy not working remotely

### ISSUE THREAD

**Issue by ScraggyMcRaggy** [FrogTheFrog/moondeck#45]
When using a remote connection PC and Buddy status on Moondeck are both _offline_.

However when using the Moonlight app connection works fine and I can see that Buddy is running. Is Moondeck using unique network settings vs the Moonlight app? 

Host - W11 PC
Client - SD OLED

**Comment by FrogTheFrog** [comment]
Ugh, firewall maybe? Buddy uses a different port for communication outside Moonlight/Sunshine.

Check this:
https://github.com/FrogTheFrog/moondeck/wiki/Troubleshooting#windowslinux-buddy-appears-offlinecannot-be-paired

**Comment by ScraggyMcRaggy** [comment]
I'm pretty sure Firewall is wide open for Buddy but I'll check once home. I'll also try port forwarding the buddy port.

**Comment by ScraggyMcRaggy** [comment]
Buddy port 5999 = Open
Buddy = Firewall open
Buddy Streamer = Firewall open

But still no luck. Status for PC and Buddy "offline" and can't access buddy direct via https://<host_ip>:59999/apiVersion

I was also the same person who had the issue with a miss-matched MAC address and fixed via the custom settings file. No idea if it's linked.

Either way, this isn't a deal breaker, but thought I would flag it to see if others have seen the same problem. If you need me to test anything just let me know.

**Comment by FrogTheFrog** [comment]
I would recommend you exit Buddy, go into Windows firewall and remove every entry for Buddy. Start it again and allow it via the Windows pop up.

I had this before with Windows where it doesn't really gives it the access to public network for whatever magical reason...

**Comment by ScraggyMcRaggy** [comment]
Didn't fix it unfortunately. Maybe this is just a network issue my side.

**Comment by FrogTheFrog** [comment]
> Buddy port 5999 = Open Buddy = Firewall open Buddy Streamer = Firewall open
> 
> But still no luck. Status for PC and Buddy "offline" and can't access buddy direct via https://<host_ip>:59999/apiVersion
> 
> I was also the same person who had the issue with a miss-matched MAC address and fixed via the custom settings file. No idea if it's linked.
> 
> Either way, this isn't a deal breaker, but thought I would flag it to see if others have seen the same problem. If you need me to test anything just let me know.

Make sure that ports are correct as you misplelled them here

I would recommend to create some sort of random server on 59999. Maybe iperf3 server?
Then would try to reach it from the internet. This would eliminate Buddy as the problem source and maybe give some other ideas.

**Comment by ScraggyMcRaggy** [comment]
Unless using UPnP I cannot access anything remotely. Confident this is due to double NAT. Basically, this is likely a local issue, not your issue.

**Comment by FrogTheFrog** [comment]
> Unless using UPnP I cannot access anything remotely. Confident this is due to double NAT. Basically, this is likely a local issue, not your issue.

In that case I'm closing the issue.
