### ISSUE TITLE
The icon of moondeck looks weird

### ISSUE THREAD

**Issue by jnlpc123** [FrogTheFrog/moondeck#46]
I remember the older version's icon is just like setting and steamcloud icon, but the latest version's icon became ugly and weird,can you change it back please!
![1710940261891161699060518193953](https://github.com/FrogTheFrog/moondeck/assets/57972366/6e266d5b-1efc-4051-9043-beb4a029d8c8)

**Comment by FrogTheFrog** [comment]
What version of SteamOS are you on?

**Comment by jnlpc123** [comment]
> What version of SteamOS are you on?

OS version 3.5.17
steam version 1710458266

**Comment by FrogTheFrog** [comment]
Is this beta or preview?

**Comment by jnlpc123** [comment]
> Is this beta or preview?

It's stable.
BTW my console is OLED
![Uploading 17109410762998313551801800638996.jpg…]()

**Comment by jnlpc123** [comment]
> 

> Will take a look after work

thanks！

**Comment by FrogTheFrog** [comment]
Use the stable release of decky please, it's broken in prerelease...

**Comment by HollyCeuin** [comment]
This is now also broken on stable it seems.

**Comment by FrogTheFrog** [comment]
There is nothing I can do except wait for Decky to fix this
https://github.com/SteamDeckHomebrew/decky-frontend-lib/pull/102

**Comment by chiyema** [comment]
Seems like the issue mentioned in decky frontend lib is resolved on June. Is there any chance they we could fix the icon?

**Comment by FrogTheFrog** [comment]
> Seems like the issue mentioned in decky frontend lib is resolved on June. Is there any chance they we could fix the icon?

You need to use the latest Decky pre-release version

**Comment by FrogTheFrog** [comment]
And MoonDeck from trsting store
