### ISSUE TITLE
"Failed to start the specific application"

### ISSUE THREAD

**Issue by ScraggyMcRaggy** [FrogTheFrog/moondeck#47]
Recently updated Sunshine + reinstalled and re-paired Moonlight Buddy (including MoonDeckStream Sunshine application).

Now when booting games via Moondeck I receive the following error: Host returned error:"Failed to start the specific application" (Error: 0)

**Comment by FrogTheFrog** [comment]
Have you even tried looking into Sunshine logs?

**Comment by ScraggyMcRaggy** [comment]
Ah really sorry. Ignore me - My Sunshine MoonDeckStream application path was incorrect. Fixed it, and error has gone away.
