### ISSUE TITLE
Icon Issue on Steam Deck Beta

### ISSUE THREAD

**Issue by dshk0718** [FrogTheFrog/moondeck#48]
Hello,

While I've been using MoonDeck for some time now, recently I've noticed this icon [issue](https://github.com/FrogTheFrog/moondeck/issues/46) pop back up.

Here is the screenshot showing that:
![image](https://github.com/FrogTheFrog/moondeck/assets/22249997/cc95c43e-287b-4f23-be7a-6da1db1e2f89)

This icon looked fine until I updated the Steam client to Steam Beta Client, which I updated to utilize the new Steam Families feature.

I know from reading the past issue that's been closed that it was due to the prerelease version of the Decky Loader. However, I am not currently using that and have not upgraded to the prerelease version and stayed on the same 2.12.0 stable version while updating to the Steam Deck Beta Client.

Additionally, I am currently on version 1.7.0 of MoonDeck.

Let me know if there is any more information you need about this issue.

**Comment by FrogTheFrog** [comment]
https://github.com/FrogTheFrog/moondeck/issues/46#issuecomment-2069356322
