### ISSUE TITLE
How to provide more configuration settings to moonlight?

### ISSUE THREAD

**Issue by DylanRJohnston** [FrogTheFrog/moondeck#49]
Moonlight now supports HDR and AV1 on the Steamdeck OLED. Since this plugin mostly just launches moonlight, is there an easy to way to pass more configuration options to Moonlight? Right now invoking moonlight manually so I can configure it properly looks substantially better than if I launch it through moondeck.

**Comment by FrogTheFrog** [comment]
What configuration options are you lacking exactly?

**Comment by DylanRJohnston** [comment]
Mainly around setting codecs, etc. However I figured out the problem was I was actually using two different moonlight apps, and if I correctly configured the one being used by moondeck the settings were left alone on launch.
