### ISSUE TITLE
MoonDeck is unable to create shortcuts

### ISSUE THREAD

**Issue by dshk0718** [FrogTheFrog/moondeck#50]
Currently, I am on SteamOS 3.6.8 and on the latest Steam Client Beta version with the Game Recordings. With that, I had to update the Decky Loader to the new 3.0.0-pre1 pre-release version (so that the Decky Loader would start working again).

Ever since I updated my Steam Deck with all the OS and client versions I mentioned above, MoonDeck (on both the stable 1.7.0 version and the testing 1.7.1 version) stopped working and would give this toast message every time I tried to run a game through MoonDeck:
![20240627111908_1](https://github.com/FrogTheFrog/moondeck/assets/22249997/f96f815a-d34b-45c5-9d61-07954fe11929)

After some digging, I've found out that the error occurred when it tried to create the shortcut with the proper app ID (which failed to retrieve the app ID I believe). I've found this console error via the developer console on Decky Loader:
![20240627112021_1](https://github.com/FrogTheFrog/moondeck/assets/22249997/86fdec07-c8aa-48b0-aee1-4134b9b1f079)

Since I have Steam Deck OLED and Steam Deck LCD, I've tried this on both with them being on the same exact versions for everything, and both failed to launch the streaming session via Moonlight.

Here are my logs:
[moondeck.log](https://github.com/user-attachments/files/16020061/moondeck.log)
(I could not find the `moondeck-runner.log` though).

**Comment by FrogTheFrog** [comment]
@dshk0718 please try the version from the Testing store

**Comment by dshk0718** [comment]
@FrogTheFrog Hey, I am glad to let you know that the new Testing version worked! Thank you so much for such a fast turn around time :+1:

**Comment by FrogTheFrog** [comment]
I will close this issue myself, once the new version is on stable

**Comment by Sterft** [comment]
Same problem here, also on the Testing branch. Every time I restart it also says 'shortcuts were removed, please restart steam client'. I also have both the OLED and LCD, but only on the OLED it seems to persist.

**Comment by FrogTheFrog** [comment]
> Hello! I would just like to report that i'm having the same issue as OP. Is it coming to stable soon? Or should i consider the testing branch?

It has been pushed to stable just a few minutes ago.

**Comment by Zonrotan** [comment]
Now that's what i call fast. Great work!
