### ISSUE TITLE
Moondeck causing Game Page flicker/refreshing

### ISSUE THREAD

**Issue by Froggerdog** [FrogTheFrog/moondeck#51]
Been trying to find the culprit for this and after removing all plugins and reinstalling decky I know it only happens with moondeck.

The page where the moondeck button appears will often refresh once choosing a game. Then, after hitting play, it will flicker as it transitions to the part with the steam deck controls animation. After exiting a game and returning to that screen more flicker/refreshing occurs. In actually gonna record a video of it actually, but I don't want to uninstall all my plugins again, just keep in mind this was happening with only moondeck installed. 

https://streamable.com/917bkj

**Comment by FrogTheFrog** [comment]
It's a known issue with plugins that inject into the UI (like HLTB).

Currently I am waiting for Decky's devs to give us some new tools for injecting into the UI. If it's no longer possible without flickering, I will come up with a new solution, but that probably won't work with gamepad navigation anymore.

**Comment by Froggerdog** [comment]
Ah I see, well thank you! 90% of my decks use is through moondeck :)

**Comment by FrogTheFrog** [comment]
This has been fixed for the Decky 3.0.0 version. Plugin is currently in testing store.
