### ISSUE TITLE
Moondeck Button Style Appears Broken

### ISSUE THREAD

**Issue by Enagan** [FrogTheFrog/moondeck#52]
Hey! 

I appreciate this is a minor issue, but for a little while now that the button put into the game detail view has been rendering in a weird system-default-looking style for me:
![PXL_20240630_160447703](https://github.com/FrogTheFrog/moondeck/assets/3987319/3a4adf57-4272-4441-8b25-f4f250e29f54)

No matter what I do, it remains in this style. I've tried removing most of my other decky plugins, including removing the CSS loader, but this does not change the look of the button.
I'm using moondeck version 1.7.1-05f574c from the deckly loader testing store.

I was wondering if there is anything that you may be aware that could be causing this.

Thanks for all your hard work. Moondeck is awesome!

**Comment by FrogTheFrog** [comment]
It's broken because of decky. Grab the prerelease version of decky if you want to get the icon back.

**Comment by Enagan** [comment]
Yup, that did it, thanks for the quick reply!
