### ISSUE TITLE
Client ignores game launch options

### ISSUE THREAD

**Issue by Bynnh0j** [FrogTheFrog/moondeck#53]
Seems moondeck just defaults to whatever the first launch option is. It would be nice if it would respect whatever game launch options are set on the host machine, or inherit the launch options that are set on the steam deck.

**Comment by FrogTheFrog** [comment]
What/which launch options are you talking about?

**Comment by Bynnh0j** [comment]
I am talking about the pop-up that some games have that let you select different rendering options, like some games allow you to choose between DX11 and DX12 when launching. It looks like moondeck will just default to using whichever option Steam arbitrarily designates as "option 1".

Another example, i have Halo MCC set on my host to launch with Easy Anti Cheat disabled. 
But steaming Halo MCC to my deck via moondeck will default to launching with EAC enabled.

**Comment by FrogTheFrog** [comment]
MoonDeck is using `steam.exe -applaunch <app_id>` command line for launching the game and that's the extent of it. If it does not remember its own settings, it's on Steam.

I'm afraid all I can say about this situation.
