### ISSUE TITLE
FEATURE REQUEST: SUNSHINE APPS SYNC

### ISSUE THREAD

**Issue by Rumik** [FrogTheFrog/moondeck#55]
Hi there.

Would it be possible to add a Sync Apps button to the main MoonDeck window? Perhaps under the Status section? I don't use the MoonDeck button as I prefer to use Sunshine app shortcuts, and having this would speed up adding new ones.

Thanks!

**Comment by FrogTheFrog** [comment]
Yeah, I'll look into it once I'm back from vacation.

**Comment by FrogTheFrog** [comment]
Same for the other issues...

**Comment by Rumik** [comment]
Thank you! GREAT plugin btw!

**Comment by FrogTheFrog** [comment]
Everything has been added. Please check moondeck shortcuts and Sunshine apps tabs in settings.

**Comment by FrogTheFrog** [comment]
You'll need to get the latest version from the testing store that works only with the latest Decky pre-release

**Comment by Rumik** [comment]
Can confirm there is now a Sync button on the main MoonDeck window! Thanks :D
