### ISSUE TITLE
FEATURE REQUEST: SET RESOLUTION AT SHORTCUT CREATION

### ISSUE THREAD

**Issue by Rumik** [FrogTheFrog/moondeck#58]
Hi there,

As I like to switch between the Internal and External displays, I prefer to set my shortcuts to the "Native" resolution. I like the fact that there's an option within the Sunshine Apps section of MoonDeck to set the resolution for all sunshine shortcuts, but would it be possible to add an option to do that automatically when the shortcuts get created? Just saves some time.

Thanks!

**Comment by FrogTheFrog** [comment]
For this one you'll have to set the app override at least once for all the apps

**Comment by Rumik** [comment]
Seems to work! Thanks :D
