### ISSUE TITLE
Possible to set HDR and 7.1 Sound via Moondeck?

### ISSUE THREAD

**Issue by nbriffa** [FrogTheFrog/moondeck#63]
As per title. This isn’t an explicit option, and I’m unsure how configs are passed through. Is this possible?

**Comment by FrogTheFrog** [comment]
Currently it is not configurable via MoonDeck, but you can just enable them in Moonlight.

MoonDeck simply provides some settings to override default ones with when launching moonlight.

**Comment by nbriffa** [comment]
Understood. Thank you! It might be worth updating that description in Moondeck to make it explicit that variables set in Moonlight will persist, and only the variables that you apply through Moondeck (Bitrate, FPS, Res, etc) will overwrite, everything else will persist.
