### ISSUE TITLE
Settings Are Still Being Loaded

### ISSUE THREAD

**Issue by sustinjimmons** [FrogTheFrog/moondeck#65]
When attempting to open Moondeck from the Decky Plugin pane, I am presented with a screen stating "Settings are still being loaded. Please wait or check the logs for exceptions". From here, unable to proceed with any kind of settings or configuration.

I have attempted to restart my Deck, as well as uninstall and reinstall Moondeck.

Steam OS 3.6.20
Steam Version 1731990050
Moondeck 1.8.0
Moondeck Buddy 1.6.2

**Comment by FrogTheFrog** [comment]
Nope, you're in the correct one...

1. Have you build this plugin yourself or is it from Decky store?
2. Can you you check what error see if you open the `CEF Console` in the Decky's `Developer` tab? It will open inspector tool and there will be another `Console` tab. It probably hidden on the small screen:
![image](https://github.com/user-attachments/assets/17ce9c09-24b5-4d83-9984-93e1045ff764)

**Comment by sustinjimmons** [comment]
Yep, I do see the Console within CEF Console. Not seeing anything related to Moondeck, but let me know if there is anything I should be looking for. Appreciate your help!

**Comment by FrogTheFrog** [comment]
Please add screenshots of that console, it might give me some hints.

**Comment by sustinjimmons** [comment]
![IMG_6449](https://github.com/user-attachments/assets/8cec6d7f-4393-4cc0-8271-69c52572758f)

this is all I’m seeing in regards to Moondeck

**Comment by sustinjimmons** [comment]
Actually, how about this:

![IMG_6450](https://github.com/user-attachments/assets/0596d530-7449-4dfa-9bc4-f0daa1aa1cec)

**Comment by FrogTheFrog** [comment]
It could be a decky issue. Could you try reinstalling Decky?

**Comment by sustinjimmons** [comment]
Sure, will do that now. I can also try installing Moondeck by myself, but not familiar with installing pnpm via npm. Any suggestions on figuring that out?

**Comment by sustinjimmons** [comment]
Ok, attempted a full wipe of Decky and reinstalled, but same issues.

**Comment by FrogTheFrog** [comment]
What about output from `sudo systemctl status plugin_loader.service`. What does it say?

**Comment by FrogTheFrog** [comment]
Please get a fresh one after SteamDeck restart

**Comment by sustinjimmons** [comment]
● plugin_loader.service - SteamDeck Plugin Loader
     Loaded: loaded (/etc/systemd/system/plugin_loader.service; enabled; preset: disabled)
     Active: active (running) since Wed 2024-11-27 13:53:36 EST; 2min 12s ago
   Main PID: 868 (PluginLoader)
      Tasks: 10 (limit: 17750)
     Memory: 176.7M (peak: 178.7M)
        CPU: 3.067s
     CGroup: /system.slice/plugin_loader.service
             ├─ 868 /home/deck/homebrew/services/PluginLoader
             ├─ 912 "Decky Loader v3.0.4 (/home/deck/homebrew/services/PluginLoader)"
             └─1119 "XR Gaming (/home/deck/homebrew/plugins/decky-XRGaming/main.py)"

Nov 27 13:53:46 steamdeck PluginLoader[912]: [loader][INFO]: Hot reload enabled
Nov 27 13:53:57 steamdeck PluginLoader[912]: [main][INFO]: Loading Decky frontend!
Nov 27 13:53:59 steamdeck PluginLoader[912]: [plugin][WARNING]: Plugin SteamGridDB is using legacy method calls. This will be remov>
Nov 27 13:53:59 steamdeck PluginLoader[912]: [plugin][WARNING]: Plugin MagicPods is using legacy method calls. This will be removed>
Nov 27 13:54:00 steamdeck PluginLoader[912]: [plugin][WARNING]: Plugin EmuDecky is using legacy method calls. This will be removed >
Nov 27 13:54:07 steamdeck PluginLoader[912]: [updater][INFO]: Updated remote version information
Nov 27 13:54:07 steamdeck PluginLoader[912]: [plugin][WARNING]: Plugin IsThereAnyDeal for Deck is using legacy method calls. This w>
Nov 27 13:54:28 steamdeck PluginLoader[912]: [injector][WARNING]: The Tab SharedJSContext socket has been disconnected while listen>
Nov 27 13:54:28 steamdeck PluginLoader[912]: [main][INFO]: CEF has disconnected...
Nov 27 13:54:38 steamdeck PluginLoader[912]: [main][INFO]: Loading Decky frontend!
lines 1-22/22 (END)

**Comment by FrogTheFrog** [comment]
It's still not a complete log it seems? Please try `sudo systemctl status plugin_loader.service -b --no-pager` after restart.

**Comment by sustinjimmons** [comment]
![image](https://github.com/user-attachments/assets/e3f0e274-2057-4d2a-af6c-57c7d23a6ca1)

Tried a double dash before b as well

**Comment by FrogTheFrog** [comment]
Yesh, I've got the wrong command. Try this:
`sudo journalctl -u plugin_loader.service -b --no-pager`

**Comment by sustinjimmons** [comment]
Dec 02 13:17:10 steamdeck systemd[1]: Started SteamDeck Plugin Loader.
Dec 02 13:17:11 steamdeck PluginLoader[992]: [main][INFO]: Starting Decky version v3.0.4
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: plugin_path: /home/deck/homebrew/plugins
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: import plugins from /home/deck/homebrew/plugins
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: found plugin: Bluetooth
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: Loaded Bluetooth
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: found plugin: EmuDecky
Dec 02 13:17:11 steamdeck PluginLoader[1048]: [sandboxed_plugin][ERROR]: Failed to start Bluetooth!
Dec 02 13:17:11 steamdeck PluginLoader[1048]: Traceback (most recent call last):
Dec 02 13:17:11 steamdeck PluginLoader[1048]:   File "PyInstaller/loader/pyimod02_importers.py", line 187, in get_code
Dec 02 13:17:11 steamdeck PluginLoader[1048]:   File "PyInstaller/loader/pyimod01_archive.py", line 134, in extract
Dec 02 13:17:11 steamdeck PluginLoader[1048]: PermissionError: [Errno 13] Permission denied: '/home/deck/homebrew/services/PluginLoader'
Dec 02 13:17:11 steamdeck PluginLoader[1048]: The above exception was the direct cause of the following exception:
Dec 02 13:17:11 steamdeck PluginLoader[1048]: Traceback (most recent call last):
Dec 02 13:17:11 steamdeck PluginLoader[1048]:   File "decky_loader/plugin/sandboxed_plugin.py", line 90, in initialize
Dec 02 13:17:11 steamdeck PluginLoader[1048]:   File "PyInstaller/loader/pyimod02_importers.py", line 400, in exec_module
Dec 02 13:17:11 steamdeck PluginLoader[1048]:   File "PyInstaller/loader/pyimod02_importers.py", line 189, in get_code
Dec 02 13:17:11 steamdeck PluginLoader[1048]: ImportError: PyiFrozenImporter cannot handle module 'decky_loader.plugin.imports.decky'
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: Loaded EmuDecky
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: found plugin: isthereanydeal-for-deck
Dec 02 13:17:11 steamdeck PluginLoader[1071]: [sandboxed_plugin][ERROR]: Failed to start EmuDecky!
Dec 02 13:17:11 steamdeck PluginLoader[1071]: Traceback (most recent call last):
Dec 02 13:17:11 steamdeck PluginLoader[1071]:   File "PyInstaller/loader/pyimod02_importers.py", line 187, in get_code
Dec 02 13:17:11 steamdeck PluginLoader[1071]:   File "PyInstaller/loader/pyimod01_archive.py", line 134, in extract
Dec 02 13:17:11 steamdeck PluginLoader[1071]: PermissionError: [Errno 13] Permission denied: '/home/deck/homebrew/services/PluginLoader'
Dec 02 13:17:11 steamdeck PluginLoader[1071]: The above exception was the direct cause of the following exception:
Dec 02 13:17:11 steamdeck PluginLoader[1071]: Traceback (most recent call last):
Dec 02 13:17:11 steamdeck PluginLoader[1071]:   File "decky_loader/plugin/sandboxed_plugin.py", line 90, in initialize
Dec 02 13:17:11 steamdeck PluginLoader[1071]:   File "PyInstaller/loader/pyimod02_importers.py", line 400, in exec_module
Dec 02 13:17:11 steamdeck PluginLoader[1071]:   File "PyInstaller/loader/pyimod02_importers.py", line 189, in get_code
Dec 02 13:17:11 steamdeck PluginLoader[1071]: ImportError: PyiFrozenImporter cannot handle module 'decky_loader.plugin.imports.decky'
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: Loaded IsThereAnyDeal for Deck
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: found plugin: moondeck
Dec 02 13:17:11 steamdeck PluginLoader[1084]: [sandboxed_plugin][ERROR]: Failed to start IsThereAnyDeal for Deck!
Dec 02 13:17:11 steamdeck PluginLoader[1084]: Traceback (most recent call last):
Dec 02 13:17:11 steamdeck PluginLoader[1084]:   File "PyInstaller/loader/pyimod02_importers.py", line 187, in get_code
Dec 02 13:17:11 steamdeck PluginLoader[1084]:   File "PyInstaller/loader/pyimod01_archive.py", line 134, in extract
Dec 02 13:17:11 steamdeck PluginLoader[1084]: PermissionError: [Errno 13] Permission denied: '/home/deck/homebrew/services/PluginLoader'
Dec 02 13:17:11 steamdeck PluginLoader[1084]: The above exception was the direct cause of the following exception:
Dec 02 13:17:11 steamdeck PluginLoader[1084]: Traceback (most recent call last):
Dec 02 13:17:11 steamdeck PluginLoader[1084]:   File "decky_loader/plugin/sandboxed_plugin.py", line 90, in initialize
Dec 02 13:17:11 steamdeck PluginLoader[1084]:   File "PyInstaller/loader/pyimod02_importers.py", line 400, in exec_module
Dec 02 13:17:11 steamdeck PluginLoader[1084]:   File "PyInstaller/loader/pyimod02_importers.py", line 189, in get_code
Dec 02 13:17:11 steamdeck PluginLoader[1084]: ImportError: PyiFrozenImporter cannot handle module 'decky_loader.plugin.imports.decky'
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: Loaded MoonDeck
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: found plugin: decky-steamgriddb
Dec 02 13:17:11 steamdeck PluginLoader[1090]: [sandboxed_plugin][ERROR]: Failed to start MoonDeck!
Dec 02 13:17:11 steamdeck PluginLoader[1090]: Traceback (most recent call last):
Dec 02 13:17:11 steamdeck PluginLoader[1090]:   File "PyInstaller/loader/pyimod02_importers.py", line 187, in get_code
Dec 02 13:17:11 steamdeck PluginLoader[1090]:   File "PyInstaller/loader/pyimod01_archive.py", line 134, in extract
Dec 02 13:17:11 steamdeck PluginLoader[1090]: PermissionError: [Errno 13] Permission denied: '/home/deck/homebrew/services/PluginLoader'
Dec 02 13:17:11 steamdeck PluginLoader[1090]: The above exception was the direct cause of the following exception:
Dec 02 13:17:11 steamdeck PluginLoader[1090]: Traceback (most recent call last):
Dec 02 13:17:11 steamdeck PluginLoader[1090]:   File "decky_loader/plugin/sandboxed_plugin.py", line 90, in initialize
Dec 02 13:17:11 steamdeck PluginLoader[1090]:   File "PyInstaller/loader/pyimod02_importers.py", line 400, in exec_module
Dec 02 13:17:11 steamdeck PluginLoader[1090]:   File "PyInstaller/loader/pyimod02_importers.py", line 189, in get_code
Dec 02 13:17:11 steamdeck PluginLoader[1090]: ImportError: PyiFrozenImporter cannot handle module 'decky_loader.plugin.imports.decky'
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: Loaded SteamGridDB
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: found plugin: decky-syncthing
Dec 02 13:17:11 steamdeck PluginLoader[1099]: [sandboxed_plugin][ERROR]: Failed to start SteamGridDB!
Dec 02 13:17:11 steamdeck PluginLoader[1099]: Traceback (most recent call last):
Dec 02 13:17:11 steamdeck PluginLoader[1099]:   File "PyInstaller/loader/pyimod02_importers.py", line 187, in get_code
Dec 02 13:17:11 steamdeck PluginLoader[1099]:   File "PyInstaller/loader/pyimod01_archive.py", line 134, in extract
Dec 02 13:17:11 steamdeck PluginLoader[1099]: PermissionError: [Errno 13] Permission denied: '/home/deck/homebrew/services/PluginLoader'
Dec 02 13:17:11 steamdeck PluginLoader[1099]: The above exception was the direct cause of the following exception:
Dec 02 13:17:11 steamdeck PluginLoader[1099]: Traceback (most recent call last):
Dec 02 13:17:11 steamdeck PluginLoader[1099]:   File "decky_loader/plugin/sandboxed_plugin.py", line 90, in initialize
Dec 02 13:17:11 steamdeck PluginLoader[1099]:   File "PyInstaller/loader/pyimod02_importers.py", line 400, in exec_module
Dec 02 13:17:11 steamdeck PluginLoader[1099]:   File "PyInstaller/loader/pyimod02_importers.py", line 189, in get_code
Dec 02 13:17:11 steamdeck PluginLoader[1099]: ImportError: PyiFrozenImporter cannot handle module 'decky_loader.plugin.imports.decky'
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: Loaded Syncthing
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: found plugin: protondb-decky
Dec 02 13:17:11 steamdeck PluginLoader[1107]: [sandboxed_plugin][ERROR]: Failed to start Syncthing!
Dec 02 13:17:11 steamdeck PluginLoader[1107]: Traceback (most recent call last):
Dec 02 13:17:11 steamdeck PluginLoader[1107]:   File "PyInstaller/loader/pyimod02_importers.py", line 187, in get_code
Dec 02 13:17:11 steamdeck PluginLoader[1107]:   File "PyInstaller/loader/pyimod01_archive.py", line 134, in extract
Dec 02 13:17:11 steamdeck PluginLoader[1107]: PermissionError: [Errno 13] Permission denied: '/home/deck/homebrew/services/PluginLoader'
Dec 02 13:17:11 steamdeck PluginLoader[1107]: The above exception was the direct cause of the following exception:
Dec 02 13:17:11 steamdeck PluginLoader[1107]: Traceback (most recent call last):
Dec 02 13:17:11 steamdeck PluginLoader[1107]:   File "decky_loader/plugin/sandboxed_plugin.py", line 90, in initialize
Dec 02 13:17:11 steamdeck PluginLoader[1107]:   File "PyInstaller/loader/pyimod02_importers.py", line 400, in exec_module
Dec 02 13:17:11 steamdeck PluginLoader[1107]:   File "PyInstaller/loader/pyimod02_importers.py", line 189, in get_code
Dec 02 13:17:11 steamdeck PluginLoader[1107]: ImportError: PyiFrozenImporter cannot handle module 'decky_loader.plugin.imports.decky'
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: Loaded ProtonDB Badges
Dec 02 13:17:11 steamdeck PluginLoader[992]: [loader][INFO]: found plugin: DeckWebBrowser
Dec 02 13:17:11 steamdeck PluginLoader[1127]: [sandboxed_plugin][ERROR]: Failed to start ProtonDB Badges!
Dec 02 13:17:11 steamdeck PluginLoader[1127]: Traceback (most recent call last):
Dec 02 13:17:11 steamdeck PluginLoader[1127]:   File "PyInstaller/loader/pyimod02_importers.py", line 187, in get_code
Dec 02 13:17:11 steamdeck PluginLoader[1127]:   File "PyInstaller/loader/pyimod01_archive.py", line 134, in extract
Dec 02 13:17:11 steamdeck PluginLoader[1127]: PermissionError: [Errno 13] Permission denied: '/home/deck/homebrew/services/PluginLoader'
Dec 02 13:17:11 steamdeck PluginLoader[1127]: The above exception was the direct cause of the following exception:
Dec 02 13:17:11 steamdeck PluginLoader[1127]: Traceback (most recent call last):
Dec 02 13:17:11 steamdeck PluginLoader[1127]:   File "decky_loader/plugin/sandboxed_plugin.py", line 90, in initialize
Dec 02 13:17:11 steamdeck PluginLoader[1127]:   File "PyInstaller/loader/pyimod02_importers.py", line 400, in exec_module
Dec 02 13:17:11 steamdeck PluginLoader[1127]:   File "PyInstaller/loader/pyimod02_importers.py", line 189, in get_code
Dec 02 13:17:11 steamdeck PluginLoader[1127]: ImportError: PyiFrozenImporter cannot handle module 'decky_loader.plugin.imports.decky'
Dec 02 13:17:12 steamdeck PluginLoader[992]: [loader][INFO]: Loaded Web Browser
Dec 02 13:17:12 steamdeck PluginLoader[992]: [loader][INFO]: found plugin: hltb-for-deck
Dec 02 13:17:12 steamdeck PluginLoader[1147]: [sandboxed_plugin][ERROR]: Failed to start Web Browser!
Dec 02 13:17:12 steamdeck PluginLoader[1147]: Traceback (most recent call last):
Dec 02 13:17:12 steamdeck PluginLoader[1147]:   File "PyInstaller/loader/pyimod02_importers.py", line 187, in get_code
Dec 02 13:17:12 steamdeck PluginLoader[1147]:   File "PyInstaller/loader/pyimod01_archive.py", line 134, in extract
Dec 02 13:17:12 steamdeck PluginLoader[1147]: PermissionError: [Errno 13] Permission denied: '/home/deck/homebrew/services/PluginLoader'
Dec 02 13:17:12 steamdeck PluginLoader[1147]: The above exception was the direct cause of the following exception:
Dec 02 13:17:12 steamdeck PluginLoader[1147]: Traceback (most recent call last):
Dec 02 13:17:12 steamdeck PluginLoader[1147]:   File "decky_loader/plugin/sandboxed_plugin.py", line 90, in initialize
Dec 02 13:17:12 steamdeck PluginLoader[1147]:   File "PyInstaller/loader/pyimod02_importers.py", line 400, in exec_module
Dec 02 13:17:12 steamdeck PluginLoader[1147]:   File "PyInstaller/loader/pyimod02_importers.py", line 189, in get_code
Dec 02 13:17:12 steamdeck PluginLoader[1147]: ImportError: PyiFrozenImporter cannot handle module 'decky_loader.plugin.imports.decky'
Dec 02 13:17:12 steamdeck PluginLoader[992]: [loader][INFO]: Plugin HLTB for Deck is passive
Dec 02 13:17:12 steamdeck PluginLoader[992]: [loader][INFO]: Loaded HLTB for Deck
Dec 02 13:17:12 steamdeck PluginLoader[992]: [loader][INFO]: found plugin: decky-XRGaming
Dec 02 13:17:12 steamdeck PluginLoader[992]: [loader][INFO]: Loaded XR Gaming
Dec 02 13:17:12 steamdeck PluginLoader[992]: [loader][INFO]: found plugin: MagicPodsDecky
Dec 02 13:17:12 steamdeck PluginLoader[1159]: /home/deck/homebrew/plugins/decky-XRGaming/main.py:145: RuntimeWarning: coroutine 'Plugin.write_control_flags' was never awaited
Dec 02 13:17:12 steamdeck PluginLoader[1159]:   self.write_control_flags({
Dec 02 13:17:12 steamdeck PluginLoader[1159]: RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Dec 02 13:17:12 steamdeck su[1163]: (to deck) root on none
Dec 02 13:17:12 steamdeck su[1163]: pam_unix(su-l:session): session opened for user deck(uid=1000) by (uid=0)
Dec 02 13:17:12 steamdeck PluginLoader[992]: [loader][INFO]: Loaded MagicPods
Dec 02 13:17:12 steamdeck PluginLoader[1170]: [sandboxed_plugin][ERROR]: Failed to start MagicPods!
Dec 02 13:17:12 steamdeck PluginLoader[1170]: Traceback (most recent call last):
Dec 02 13:17:12 steamdeck PluginLoader[1170]:   File "PyInstaller/loader/pyimod02_importers.py", line 187, in get_code
Dec 02 13:17:12 steamdeck PluginLoader[1170]:   File "PyInstaller/loader/pyimod01_archive.py", line 134, in extract
Dec 02 13:17:12 steamdeck PluginLoader[1170]: PermissionError: [Errno 13] Permission denied: '/home/deck/homebrew/services/PluginLoader'
Dec 02 13:17:12 steamdeck PluginLoader[1170]: The above exception was the direct cause of the following exception:
Dec 02 13:17:12 steamdeck PluginLoader[1170]: Traceback (most recent call last):
Dec 02 13:17:12 steamdeck PluginLoader[1170]:   File "decky_loader/plugin/sandboxed_plugin.py", line 90, in initialize
Dec 02 13:17:12 steamdeck PluginLoader[1170]:   File "PyInstaller/loader/pyimod02_importers.py", line 400, in exec_module
Dec 02 13:17:12 steamdeck PluginLoader[1170]:   File "PyInstaller/loader/pyimod02_importers.py", line 189, in get_code
Dec 02 13:17:12 steamdeck PluginLoader[1170]: ImportError: PyiFrozenImporter cannot handle module 'decky_loader.plugin.imports.decky'
Dec 02 13:17:12 steamdeck su[1163]: pam_unix(su-l:session): session closed for user deck
Dec 02 13:17:12 steamdeck PluginLoader[1159]: Error checking driver installation b'Verification failed\n'
Dec 02 13:17:12 steamdeck PluginLoader[1159]: Installing breezy for plugin version 1.0.2
Dec 02 13:17:12 steamdeck su[1483]: (to deck) root on none
Dec 02 13:17:12 steamdeck su[1483]: pam_unix(su-l:session): session opened for user deck(uid=1000) by (uid=0)
Dec 02 13:17:13 steamdeck su[1483]: pam_unix(su-l:session): session closed for user deck
Dec 02 13:17:13 steamdeck su[1505]: (to deck) root on none
Dec 02 13:17:13 steamdeck su[1505]: pam_unix(su-l:session): session opened for user deck(uid=1000) by (uid=0)
Dec 02 13:17:13 steamdeck su[1505]: pam_unix(su-l:session): session closed for user deck
Dec 02 13:17:13 steamdeck sudo[1524]:     root : PWD=/tmp/xr-driver-IZNiMdzNjT/xr_driver ; USER=root ; COMMAND=/usr/bin/rm /usr/lib/udev/rules.d/70-*-xr.rules
Dec 02 13:17:13 steamdeck sudo[1524]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Dec 02 13:17:13 steamdeck sudo[1524]: pam_unix(sudo:session): session closed for user root
Dec 02 13:17:13 steamdeck sudo[1533]:     root : PWD=/tmp/xr-driver-IZNiMdzNjT/xr_driver ; USER=root ; COMMAND=/usr/bin/rm /etc/udev/rules.d/70-rayneo-xr.rules /etc/udev/rules.d/70-rokid-xr.rules /etc/udev/rules.d/70-uinput-xr.rules /etc/udev/rules.d/70-viture-xr.rules /etc/udev/rules.d/70-xreal-xr.rules
Dec 02 13:17:13 steamdeck sudo[1533]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Dec 02 13:17:13 steamdeck sudo[1533]: pam_unix(sudo:session): session closed for user root
Dec 02 13:17:13 steamdeck su[1558]: (to deck) root on none
Dec 02 13:17:13 steamdeck su[1558]: pam_unix(su:session): session opened for user deck(uid=1000) by (uid=0)
Dec 02 13:17:13 steamdeck su[1558]: pam_unix(su:session): session closed for user deck
Dec 02 13:17:13 steamdeck su[1663]: (to deck) root on none
Dec 02 13:17:13 steamdeck su[1663]: pam_unix(su-l:session): session opened for user deck(uid=1000) by (uid=0)
Dec 02 13:17:14 steamdeck su[1663]: pam_unix(su-l:session): session closed for user deck
Dec 02 13:17:14 steamdeck su[1839]: (to deck) root on none
Dec 02 13:17:14 steamdeck su[1839]: pam_unix(su-l:session): session opened for user deck(uid=1000) by (uid=0)
Dec 02 13:17:14 steamdeck su[1839]: pam_unix(su-l:session): session closed for user deck
Dec 02 13:17:21 steamdeck PluginLoader[992]: [loader][INFO]: Hot reload enabled
Dec 02 13:17:32 steamdeck PluginLoader[992]: [main][INFO]: Loading Decky frontend!
Dec 02 13:17:34 steamdeck PluginLoader[992]: [plugin][WARNING]: Plugin SteamGridDB is using legacy method calls. This will be removed in a future release.
Dec 02 13:17:34 steamdeck PluginLoader[992]: [plugin][WARNING]: Plugin MagicPods is using legacy method calls. This will be removed in a future release.
Dec 02 13:17:36 steamdeck PluginLoader[992]: [plugin][WARNING]: Plugin EmuDecky is using legacy method calls. This will be removed in a future release.
Dec 02 13:17:42 steamdeck PluginLoader[992]: [updater][INFO]: Updated remote version information
Dec 02 13:17:57 steamdeck PluginLoader[992]: [plugin][WARNING]: Plugin IsThereAnyDeal for Deck is using legacy method calls. This will be removed in a future release.
Dec 02 13:18:02 steamdeck PluginLoader[992]: [injector][WARNING]: The Tab SharedJSContext socket has been disconnected while listening for messages.
Dec 02 13:18:02 steamdeck PluginLoader[992]: [main][INFO]: CEF has disconnected...
Dec 02 13:18:12 steamdeck PluginLoader[992]: [main][INFO]: Loading Decky frontend!

**Comment by sustinjimmons** [comment]
Perhaps a permissions error for the Plugin Loader service? I am assuming that is installed when installing Decky Loader.

**Comment by FrogTheFrog** [comment]
> Perhaps a permissions error for the Plugin Loader service? I am assuming that is installed when installing Decky Loader.

Yes, that IS the Deckly Loader (I think it's an old name). Anyway, you should ask on Decky's discord for help. One last question though, how do you install Decky?

**Comment by FrogTheFrog** [comment]
Actually it does not matter, please try this:
1. `curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/uninstall.sh | sh`
2. Reboot SteamDeck
3. `curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/install_release.sh | sh`
4. Reboot SteamDeck
5. Check if it works

**Comment by sustinjimmons** [comment]
> > Perhaps a permissions error for the Plugin Loader service? I am assuming that is installed when installing Decky Loader.
> 
> Yes, that IS the Deckly Loader (I think it's an old name). Anyway, you should ask on Decky's discord for help. One last question though, how do you install Decky?

Using their Github page. Downloaded the latest release, renamed it and moved to the desktop, ran as admin and installed the stable release.



> Actually it does not matter, please try this:
> 
>     1. `curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/uninstall.sh | sh`
> 
>     2. Reboot SteamDeck
> 
>     3. `curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/install_release.sh | sh`
> 
>     4. Reboot SteamDeck
> 
>     5. Check if it works

But will attempt this now!

**Comment by sustinjimmons** [comment]
Yeah, same error

**Comment by FrogTheFrog** [comment]
Oh, well then please ask for help on discord :/

**Comment by sustinjimmons** [comment]
```
sudo chmod 755 /home/deck/homebrew/services/
sudo chmod 755 /home/deck/homebrew/services/.systemd/
sudo chmod 644 /home/deck/homebrew/services/.loader.version
sudo chmod 777 /home/deck/homebrew/services/PluginLoader
sudo chmod 644 /home/deck/homebrew/services/.systemd/*
```

**Comment by sustinjimmons** [comment]
Posted on the discord and this seemed to fix the issues:

Run the following commands in Konsole

sudo chmod 755 /home/deck/homebrew/services/
sudo chmod 755 /home/deck/homebrew/services/.systemd/
sudo chmod 644 /home/deck/homebrew/services/.loader.version
sudo chmod 777 /home/deck/homebrew/services/PluginLoader
sudo chmod 644 /home/deck/homebrew/services/.systemd/*

Then run `sudo chown -R root:root /home/deck/homebrew/services/* && sudo systemctl restart plugin_loader.service`

Moondeck settings are appearing again. Will deep dive test soon!

**Comment by sustinjimmons** [comment]
Tested and everything worked like a charm. Appreciate the help!
