### ISSUE TITLE
Shutdown PC only closes Moondeck Buddy

### ISSUE THREAD

**Issue by crudelios** [FrogTheFrog/moondeck#67]
Hi!

First, I'm not sure if this issue is related to Moondeck or to Moondeck Buddy.

As the title says, when I press the "Shutdown PC" button on Steam Deck's Moondeck, only Moondeck Buddy closes, but the PC never shuts down.

Maybe I'm missing something?

This is on a recent install of both Moondeck and Moondeck Buddy.

Thanks!

**Comment by FrogTheFrog** [comment]
Please provide logs from the Buddy.

**Comment by crudelios** [comment]
Will do ASAP!

**Comment by crudelios** [comment]
This is really odd.

Now that I'm trying to reproduce the issue to get the logs, everything is working fine.

But the last times I tried, it didn't shut down anything.

I have another request though as it may help: can you create a backup of the last log when starting the app, please? Because otherwise if I get another issue when shutting down, the log will be overwritten when I reboot the computer.

Anyway I'm closing this for now. If the issue reappears I'll let you know.
