### ISSUE TITLE
tkinter on bazzite

### ISSUE THREAD

**Issue by 522122** [FrogTheFrog/moondeck#68]
Running bazzite on Rog Ally X.

Fresh install of moondeck and clicking icon to lunch game does nothing.
After some investigation I noticed duplicate shortcuts on host, so I checked what should it run.
When running the script manually on client I got error related to import of `tkinter` in `defaults/python/lib/wolsplashscreen.py`

Apparently bazzite's python ships without this.
 
My local ghetto fix was to install python-tk via brew and modify `defaults/python/moondeckrun.sh` to use the correct python. Will I loose my edit on update?

Sry I'm not a python dev and know very little about these things. Maybe there is something you can do to make it work out of the box on atomic distro?

**Comment by FrogTheFrog** [comment]
Yes, the changes will be lost. I would package tkinter if I could, but sadly I can't...

I'm not familiar with bazzite, but why/how do you need to modify the script to use the correct python?

**Comment by 522122** [comment]
Because the script runs python with absolute path
`/usr/bin/python`
which is unable to import tkinter and I need to run something like:
`/home/linuxbrew/.linuxbrew/bin/python3` 
which is the version I installed with brew install python-tk

**Comment by FrogTheFrog** [comment]
Can you run `whereis /usr/local/bin/python` for me?

**Comment by FrogTheFrog** [comment]
If you can come up with a portable solution, I'm all up for it. I'm leaning towards using `MOONDECK_PYTHON` export or something that could be provided from the outside if python location cannot be inferred via predictable paths, like `/usr/local/bin/python`

**Comment by 522122** [comment]
```
bazzite@bazzite:~$ whereis /usr/local/bin/python
python: /usr/bin/python /usr/share/man/man1/python.1.gz
bazzite@bazzite:~$ 
```

I think I found solution for me that will survive update of moondeck

Used `rpm-ostree install python-tkinter`

after that python from /usr/bin/ can import tkinter

```bazzite@bazzite:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:84712e223557d8eb2c3d0ba7fc39070715f6ba796463326405de4bd7d9116a10
                  Version: 41.20241216 (2024-12-16T05:01:17Z)
          LayeredPackages: python-tkinter

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:84712e223557d8eb2c3d0ba7fc39070715f6ba796463326405de4bd7d9116a10
                  Version: 41.20241216 (2024-12-16T05:01:17Z)
bazzite@bazzite:~$ 
```

**Comment by FrogTheFrog** [comment]
Ok, so the problem is solved then. Still, if you want a different approach, please submit a PR that works on bazzite and should work on other distros (I can verify it on SteamOS if needed).
