### ISSUE TITLE
Error when trying to start games through moondeck

### ISSUE THREAD

**Issue by zdaar** [FrogTheFrog/moondeck#9]
Hi,

When I start a Steam Game through the moondeck icon it will open moonlight, say "Loading app list" , then error out saying "Failed to find application MoonDeckStream".
Then it exists back to steamos.
Moonlight is working fine in standalone.

Issue persists through deck and host (win10) reboot.
Moonlight updated to latest version (4.3.1) and downloaded as flatpak.

Had the problem with gamestream so I switched to sunshine and its the same issue.

Can you help ?

Thx !

**Comment by FrogTheFrog** [comment]
Heyo, did you follow the updated instructions to setup moondeck buddy for Sunshine?

**Comment by KarmicBacklash** [comment]
I'm also having the same issue. I'm having a hard time trying to understand what might be the issue.

**Comment by FrogTheFrog** [comment]
@KarmicBacklash at the end of https://github.com/FrogTheFrog/moondeck-buddy, there is a section about the setup for Sunshine. Did you follow these steps?

**Comment by KarmicBacklash** [comment]
Yes, to the letter. The path is not the same but it does link to the same executable. I've done some testing and I also believe it's not a network issue, as the other said the moonlight application works just fine.

**Comment by FrogTheFrog** [comment]
> 

When you open Moonlight, can you confirm that MoonDeckStream is in the app list? Maybe you still have Nvidia gamestream enabled?

**Comment by KarmicBacklash** [comment]
I've double and triple checked, I even removed the entry I made and readded it, same issue. I went as far as to disable Nvidia gamestream to see if that would change anything. It did not.

**Comment by FrogTheFrog** [comment]
The error `Failed to find application MoonDeckStream` is produced by Moonlight if it cannot find it in the app list that Sunshine provides. Could you post a screenshot showing it's in the Moonlight app list? Or maybe we could continue this conversation on Decky's discord?

**Comment by FrogTheFrog** [comment]
Closing the issue due to inactivity.
